- hosts: localhost    
  connection: local
  become: true

  pre_tasks:
    - name: update repos (debian)
      when: ansible_distribution in ["Debian", "Ubuntu"]
      apt:
        update_cache: yes
      changed_when: False
  
  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml

