- hosts: localhost    
  connection: local
  become: true

  tasks:
  - name: Install packages
    apt:
      name: 
       - htop
       - zsh
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common
       - cockpit
       - wget
       - chsh

  - name: Just ensuring the repo checkout exists
    git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: no

  - name: Just ensuring the repo checkout exists
    git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    update: no

