- name: Install packages
  apt:
    name: 
       - htop
       - zsh
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common
       - cockpit
       - wget
       - neofetch


